### ISSUE TITLE
/newcorpus request returns 200 OK and corpusadded=true on fail

### ISSUE THREAD

**Issue by jrwdunham** [OpenSourceFieldlinguistics/AuthenticationWebService#33]
Try adding a corpus with the same name as an existing one. HTTP response is 200 and the body JSON is.

    {"corpusadded": true, "userFriendlyErrors": ["There was an error creating your corpus. Tagalog"]}

Shouldn't there be a 400+ error and shouldn't `corpusadded` be `false`?

**Comment by cesine** [comment]
@jrwdunham this is fixed in the refactor, the server now uses status codes :(
